apiVersion: v2
name: cloudsync
description: Helm Chart for periodically synchronizing cloud storage

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.3.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.62.2

home: https://rclone.org/
icon: https://rclone.org/img/logo_on_light__horizontal_color.svg

maintainers:
  - name: Ian Martin
    email: ian@imartin.net

keywords:
  - rclone
  - s3
  - arq
  - backup
