# Default values for webserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

persistentVolume:
  size: 1Gi
  accessMode: ReadOnlyMany
  storageClass: ""

nginx:
  staticSitePVC:
  service:
    type: ClusterIP
    externalTrafficPolicy: ""
  serverBlock: ""
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 90
  resources:
    limits:
      cpu: 1000m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
      selector:
        release: prometheus
      namespace: metrics
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 16Mi
