apiVersion: v2
name: emby
description: A Helm chart for Emby Media Server. Run as a StatefulSet on kubernetes, so that volume management is safely done.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.8

appVersion: 4.9.1.90

sources:
  - https://github.com/MediaBrowser/Emby
  - https://github.com/MediaBrowser/Emby.Build

icon: https://avatars3.githubusercontent.com/u/3607473?s=200&v=4

maintainers:
  - name: Ian Martin
    email: ian@imartin.net
    url: https://imartin.net
