{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tdarr.fullname" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
