{{- range $volumeName, $volumeConfig := .Values.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.fullname" $ }}-{{ $volumeName }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "samba.labels" $ | nindent 4 }}
spec:
  {{- if $volumeConfig.storageClass }}
  storageClassName: {{ $volumeConfig.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ $volumeConfig.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ $volumeConfig.accessMode | default "ReadWriteOnce" }}
{{- end }}
