apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samba.fullname" . }}-users
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "samba.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $uid := .Values.config.groups }}
  GROUP_{{ $name | lower }}: {{ $uid | default "" | quote | b64enc }}
  {{- end }}
  {{- range $name, $config := .Values.config.accounts }}
  ACCOUNT_{{ $name | lower }}: {{ $config.password | b64enc }}
  {{- if $config.uid }}
  UID_{{ $name | lower }}: {{ $config.uid | default "" | quote | b64enc }}
  {{- end }}
  {{- with $config.groups }}
  GROUPS_{{ $name | lower }}: {{ join "," . | b64enc }}
  {{- end }}
  {{- end }}
