apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smb
      protocol: TCP
      name: smb
  selector:
    {{- include "samba.selectorLabels" . | nindent 4 }}
