{{- if or .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}
  labels: {{ include "transmission.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.auth.username }}"
  password: "{{ .Values.auth.password }}"
{{- end }}
