{{- if .Values.vpn.conf }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-vpn
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
  vpn.conf: {{ .Values.vpn.conf | toString | b64enc | quote }}
{{- end }}
