apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-echo.fullname" . }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (and .Values.tls.cert .Values.tls.key) .Values.tls.secret.reference }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "http-echo.selectorLabels" . | nindent 4 }}
