{{- if and .Values.tls.cert .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "http-echo.fullname" . }}-tls
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
